// Compiles the standard TON jetton contracts (ton-blockchain/token-contract, ft/)
// from ./contracts/jetton and writes their code BOCs to src/contracts/jettonCode.ts.
import { compileFunc } from '@ton-community/func-js'
import { readFileSync, writeFileSync } from 'node:fs'
import { Cell } from '@ton/core'

const dir = new URL('../contracts/jetton/', import.meta.url)
const sources = Object.fromEntries(
  ['stdlib.fc', 'params.fc', 'op-codes.fc', 'discovery-params.fc', 'jetton-utils.fc', 'jetton-minter-discoverable.fc', 'jetton-wallet.fc']
    .map((f) => [f, readFileSync(new URL(f, dir), 'utf8')]),
)

async function compile(targets) {
  const res = await compileFunc({ targets, sources })
  if (res.status === 'error') throw new Error(res.message)
  return res.codeBoc
}

const minter = await compile(['stdlib.fc', 'params.fc', 'op-codes.fc', 'discovery-params.fc', 'jetton-utils.fc', 'jetton-minter-discoverable.fc'])
const wallet = await compile(['stdlib.fc', 'params.fc', 'op-codes.fc', 'jetton-utils.fc', 'jetton-wallet.fc'])

const hash = (b64) => Cell.fromBase64(b64).hash().toString('hex')
const out = `// AUTO-GENERATED by scripts/compile-jetton.mjs — do not edit.
// Source: https://github.com/ton-blockchain/token-contract (ft/jetton-minter-discoverable.fc, ft/jetton-wallet.fc)
export const JETTON_MINTER_CODE_BOC = '${minter}'
// code hash: ${hash(minter)}
export const JETTON_WALLET_CODE_BOC = '${wallet}'
// code hash: ${hash(wallet)}
`
writeFileSync(new URL('../src/contracts/jettonCode.ts', import.meta.url), out)
console.log('minter', hash(minter))
console.log('wallet', hash(wallet))
